import { UserInfo } from "@/lib/store";
import { randomUUID } from "expo-crypto";

export const SampleData: UserInfo[] = [
  {
    userId: randomUUID(),
    name: "Priya Patel",
    birthDate: new Date(),
    gender: "Female",
    hearingStatus: "Yes, I have hearing loss",
    address: "Mumbai",
    contactNumber: "1234567890",
    photo: "photo_url_1",
  },
  {
    userId: randomUUID(),
    name: "Vijay Agvanti",
    birthDate: new Date(),
    gender: "Male",
    hearingStatus: "Yes, I have hearing loss",
    address: "Pune",
    contactNumber: "1234567890",
    photo: "photo_url_2",
  },
  {
    userId: randomUUID(),
    name: "Anita Sharma",
    birthDate: new Date(1987, 4, 23),
    gender: "Female",
    hearingStatus: "No, I have no hearing loss",
    address: "Delhi",
    contactNumber: "9876543210",
    photo: "photo_url_3",
  },
  {
    userId: randomUUID(),
    name: "Rohit Mehra",
    birthDate: new Date(1990, 7, 17),
    gender: "Male",
    hearingStatus: "Yes, I have hearing loss",
    address: "Chennai",
    contactNumber: "9876543120",
    photo: "photo_url_4",
  },
  {
    userId: randomUUID(),
    name: "Sara Khan",
    birthDate: new Date(1995, 11, 11),
    gender: "Female",
    hearingStatus: "No, I have no hearing loss",
    address: "Hyderabad",
    contactNumber: "9654321098",
    photo: "photo_url_5",
  },
  {
    userId: randomUUID(),
    name: "Aman Verma",
    birthDate: new Date(2000, 6, 5),
    gender: "Male",
    hearingStatus: "No, I have no hearing loss",
    address: "Bangalore",
    contactNumber: "9765432180",
    photo: "photo_url_6",
  },
  {
    userId: randomUUID(),
    name: "Neha Gupta",
    birthDate: new Date(1998, 2, 22),
    gender: "Female",
    hearingStatus: "Yes, I have hearing loss",
    address: "Kolkata",
    contactNumber: "9876543109",
    photo: "photo_url_7",
  },
];
